# Generated by Django 4.0.5 on 2022-06-15 11:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_alter_member_avatar'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_event', models.CharField(max_length=50, null=True)),
                ('teaser', models.CharField(max_length=50, null=True)),
                ('content_event', models.CharField(max_length=850, null=True)),
                ('date_event', models.DateTimeField(blank=True, null=True, verbose_name='date_event')),
                ('location_event', models.CharField(max_length=250, null=True)),
                ('image_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ListEvents',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('teaser', models.TextField(null=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='speakers', to='event.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speakers', to='member.member')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('teaser', models.TextField(null=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='event.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='member.member')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
