# Generated by Django 4.0.5 on 2022-06-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('event', '0002_listeventsochi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListEvents',
            new_name='LocalEvent',
        ),
        migrations.DeleteModel(
            name='listEventSochi',
        ),
    ]
