# Generated by Django 4.0.5 on 2022-06-15 12:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_listevents_localevent_delete_listeventsochi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindex',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='LocalEvent',
        ),
    ]
