# Generated by Django 4.0.5 on 2022-06-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventindex_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindex',
            name='intro',
        ),
    ]
