# Generated by Django 4.0.5 on 2022-06-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_homepageblocks_remove_eventindex_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageBlocks',
        ),
    ]
