# Generated by Django 4.0.5 on 2022-06-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_сarouselnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='СarouselNews',
        ),
    ]
