# Generated by Django 4.0.5 on 2022-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_organizerslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryOrganizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slag', models.SlugField(allow_unicode=True, help_text='Выбрать категорию для Организатора', verbose_name='slag_category_org')),
            ],
            options={
                'verbose_name': 'Блок выбора категории организатора',
                'verbose_name_plural': 'Блок выбора категории организаторов',
                'ordering': ['name'],
            },
        ),
    ]
