# Generated by Django 4.0.5 on 2022-07-06 09:53

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_blogcategoryorganizers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategoryorganizers',
            options={},
        ),
        migrations.AddField(
            model_name='organizers',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='event.blogcategoryorganizers'),
        ),
    ]
