# Generated by Django 4.0.5 on 2022-07-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_blogcategoryorganizers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategoryorganizers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogcategoryorganizers',
            name='slag',
        ),
    ]
