# Generated by Django 4.0.5 on 2022-07-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_blogcategoryorganizers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategoryorganizers',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogcategoryorganizers',
            name='slag',
            field=models.SlugField(allow_unicode=True, help_text='Выбрать категорию для Организатора', null=True, verbose_name='slag_category_org'),
        ),
    ]
