# Generated by Django 4.0.5 on 2022-07-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_blogcategoryorganizers_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategoryorganizers',
            options={'verbose_name': 'Организатор и  Контрибьютор', 'verbose_name_plural': 'Организаторы и  Контрибьюторы'},
        ),
    ]
