# Generated by Django 4.0.5 on 2022-06-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
    ]
