# Generated by Django 4.0.5 on 2022-06-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_body_homepage_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='stream',
            new_name='body',
        ),
    ]
