# Generated by Django 4.0.5 on 2022-06-21 15:41

from django.db import migrations, models
import home.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_stream_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('icon_svg', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hello', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock()), ('call_to_action_label', wagtail.blocks.CharBlock()), ('call_to_action_link', wagtail.blocks.URLBlock())])), ('html', wagtail.blocks.RawHTMLBlock()), ('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('carousel', home.models.EventCarousel())], null=True, use_json_field=True),
        ),
    ]
