# Generated by Django 4.0.5 on 2022-06-27 10:13

from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sociallink_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hello', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock()), ('call_to_action_label', wagtail.blocks.CharBlock()), ('call_to_action_link', wagtail.blocks.URLBlock())])), ('CallToActionWithSocial', wagtail.blocks.StructBlock([('call_to_action_label', wagtail.blocks.CharBlock()), ('call_to_action_link', wagtail.blocks.URLBlock())])), ('html', wagtail.blocks.RawHTMLBlock()), ('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('carousel', home.models.EventCarousel())], null=True, use_json_field=True),
        ),
    ]
