# Generated by Django 4.0.5 on 2022-07-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_menu_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Раздел заголовка HEADER', 'verbose_name_plural': 'Разделы заголовка HEADER'},
        ),
        migrations.AlterModelOptions(
            name='partnerlink',
            options={'verbose_name': 'Спонсор', 'verbose_name_plural': 'Спонсоры'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Наша социальная сеть', 'verbose_name_plural': 'Наши социальные сети'},
        ),
    ]
